"""
Load raw CSV / JSONL files from data/raw/ into Snowflake schema RAW, one table per report sheet.

Design choice: the raw layer keeps every column as VARCHAR plus _loaded_at and _source_file.
Typing, renaming, and de-duplication belong to dbt staging models — so a load can always be replayed.

Table and column descriptions come from every dbt/models/staging/*/_*__sources.yml (_ym__sources.yml is generated by
scripts/gen_sources_yml.py, _finance__sources.yml is hand-written) and are written to Snowflake as COMMENTs after each
load — one source of truth for docs.

Usage:
  python ingest/load_to_snowflake.py                 # loads everything under data/raw not yet loaded, then comments
  python ingest/load_to_snowflake.py --reload        # truncates and reloads all
  python ingest/load_to_snowflake.py --comments-only # no load: (re)apply descriptions from the yaml to RAW
  python ingest/load_to_snowflake.py --comments-only --dry-run   # print the COMMENT statements, no connection

Env (.env): SNOWFLAKE_ACCOUNT, SNOWFLAKE_USER, SNOWFLAKE_PRIVATE_KEY_PATH, SNOWFLAKE_ROLE, SNOWFLAKE_WAREHOUSE=dbt_wh,
            SNOWFLAKE_DATABASE=marketplace, SNOWFLAKE_RAW_SCHEMA=raw
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import pathlib
import re

import pandas as pd
import yaml
from dotenv import load_dotenv

load_dotenv()
ROOT = pathlib.Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "data" / "raw"
MANIFEST = RAW_DIR / "_loaded.txt"      # one loaded file path per line (git-ignored with data/)
SOURCES_YMLS = sorted((ROOT / "dbt" / "models" / "staging").glob("*/_*__sources.yml"))   # one per dbt source (yandex_market, finance)


def table_name(report_dir: str, file: pathlib.Path) -> str:
    """CSV: united_orders/<run>/<period>/orders_and_offers_transactions.csv → UNITED_ORDERS_ORDERS_AND_OFFERS_TRANSACTIONS
       (one table per report sheet / appendix).
       JSONL: stock_snapshots/<run>/stocks.jsonl, orders_stats/<run>/<period>.jsonl, offer_mappings/... → one table per
       endpoint, named after the directory (file names there carry the period, not the shape)."""
    if file.suffix == ".jsonl":
        return report_dir.upper()
    sheet = re.sub(r"[^a-z0-9]+", "_", file.stem.lower()).strip("_")
    return f"{report_dir}_{sheet}".upper()


def read_any(file: pathlib.Path) -> pd.DataFrame:
    if file.suffix == ".jsonl":
        # Keep nested objects/arrays (items, commissions, stocks, offer…) as JSON text → parse_json() in staging.
        rows = []
        with file.open(encoding="utf-8") as fh:
            for line in fh:
                if line.strip():
                    obj = json.loads(line)
                    row = {k: (json.dumps(v, ensure_ascii=False) if isinstance(v, (dict, list)) else v)
                           for k, v in obj.items()}
                    row["_raw_json"] = json.dumps(obj, ensure_ascii=False)   # whole record, for parse_json() in staging
                    rows.append(row)
        df = pd.DataFrame(rows)
        df = df[sorted(df.columns)]          # optional keys appear in different orders across files
    else:
        df = pd.read_csv(file, dtype=str, sep=None, engine="python")   # sep=None: sniff ',' vs ';'
    df.columns = [re.sub(r"[^A-Za-z0-9]+", "_", c).strip("_").upper() for c in df.columns]
    df["_LOADED_AT"] = dt.datetime.now(dt.timezone.utc).isoformat()
    df["_SOURCE_FILE"] = str(file.relative_to(RAW_DIR))
    return df.where(df.notna(), None).astype(object)


def ensure_table(conn, tbl: str, columns: list[str], recreate: bool = False) -> None:
    """RAW tables are all-VARCHAR by design (typing is staging's job) — never let write_pandas infer types from data
    (an empty first file would make columns NUMBER and the next file fails with 'Numeric value … is not recognized').
    Creates the table if missing; adds columns that appear later (report structure may grow)."""
    cur = conn.cursor()
    if recreate:
        cur.execute(f"drop table if exists {tbl}")
    cur.execute(f"create table if not exists {tbl} ({', '.join(f'{c} varchar' for c in columns)})")
    existing = {row[0].upper() for row in cur.execute(f"describe table {tbl}").fetchall()}
    for c in columns:
        if c.upper() not in existing:
            cur.execute(f"alter table {tbl} add column {c} varchar")
            print(f"  {tbl}: added column {c}")


def load_descriptions(paths: list[pathlib.Path] = SOURCES_YMLS) -> dict[str, tuple[str, dict[str, str]]]:
    """{TABLE_IDENTIFIER: (table description, {COLUMN: description})} from every dbt sources yaml under models/staging."""
    out = {}
    for path in paths:
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        for src in doc["sources"]:
            for t in src["tables"]:
                cols = {c["name"].upper(): (c.get("description") or "").strip() for c in t.get("columns", [])}
                out[(t.get("identifier") or t["name"]).upper()] = ((t.get("description") or "").strip(), cols)
    return out


def comment_statements(descriptions: dict, existing_columns: dict[str, set[str]] | None = None) -> list[str]:
    """COMMENT ON … statements for every documented table/column. When existing_columns is given (from DESCRIBE TABLE),
    tables and columns that are not in Snowflake yet are skipped — the yaml may be ahead of the warehouse."""
    def q(text: str) -> str:
        return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"

    stmts = []
    for tbl, (tdesc, cols) in descriptions.items():
        if existing_columns is not None and tbl not in existing_columns:
            continue
        if tdesc:
            stmts.append(f"comment on table {tbl} is {q(tdesc)}")
        for col, cdesc in cols.items():
            if not cdesc or cdesc == "TODO":
                continue
            if existing_columns is not None and col not in existing_columns[tbl]:
                continue
            stmts.append(f"comment on column {tbl}.{col} is {q(cdesc)}")
    return stmts


def apply_comments(conn, tables: set[str] | None = None) -> None:
    """Push descriptions from the dbt yaml to Snowflake (all documented RAW tables, or just `tables`)."""
    descriptions = load_descriptions()
    if tables is not None:
        descriptions = {t: d for t, d in descriptions.items() if t in tables}
    cur = conn.cursor()
    existing = {}
    for tbl in descriptions:
        try:
            existing[tbl] = {row[0].upper() for row in cur.execute(f"describe table {tbl}").fetchall()}
        except Exception:                                   # table not created yet (no data for it so far)
            continue
    stmts = comment_statements(descriptions, existing)
    for stmt in stmts:
        cur.execute(stmt)
    print(f"comments: {len(stmts)} statements over {len(existing)} tables")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--reload", action="store_true")
    ap.add_argument("--comments-only", action="store_true", help="only (re)apply table/column descriptions from the yaml")
    ap.add_argument("--dry-run", action="store_true", help="with --comments-only: print the statements, don't connect")
    a = ap.parse_args()

    if a.comments_only and a.dry_run:
        for stmt in comment_statements(load_descriptions()):
            print(stmt + ";")
        return

    import snowflake.connector
    from snowflake.connector.pandas_tools import write_pandas

    loaded = set(MANIFEST.read_text().splitlines()) if MANIFEST.exists() and not a.reload else set()
    conn = snowflake.connector.connect(
        account=os.environ["SNOWFLAKE_ACCOUNT"], user=os.environ["SNOWFLAKE_USER"],
        private_key_file=os.environ["SNOWFLAKE_PRIVATE_KEY_PATH"],      # key-pair auth, service user
        role=os.environ.get("SNOWFLAKE_ROLE", "SYSADMIN"), warehouse=os.environ.get("SNOWFLAKE_WAREHOUSE", "DBT_WH"),
        database=os.environ.get("SNOWFLAKE_DATABASE", "MARKETPLACE"), schema=os.environ.get("SNOWFLAKE_RAW_SCHEMA", "RAW"),
    )
    if a.comments_only:
        apply_comments(conn)
        conn.close()
        return

    prepared: set[str] = set()
    files = sorted(p for p in RAW_DIR.rglob("*") if p.suffix in (".csv", ".jsonl"))
    for f in files:
        rel = str(f.relative_to(RAW_DIR))
        if rel in loaded:
            continue
        report_dir = f.relative_to(RAW_DIR).parts[0]
        tbl = table_name(report_dir, f)
        df = read_any(f)
        ensure_table(conn, tbl, list(df.columns), recreate=a.reload and tbl not in prepared)
        prepared.add(tbl)
        if len(df) == 0:                                   # header-only file (e.g. an empty appendix): nothing to copy
            print(f"{rel} → {tbl}: 0 rows (empty file)")
        else:
            ok, _, nrows, _ = write_pandas(conn, df, tbl, auto_create_table=False, overwrite=False, quote_identifiers=False)
            print(f"{rel} → {tbl}: {nrows} rows, ok={ok}")
        loaded.add(rel)
    MANIFEST.write_text("\n".join(sorted(loaded)))
    if prepared:                                           # new/changed tables: refresh their descriptions
        apply_comments(conn, prepared)
    conn.close()


if __name__ == "__main__":
    main()
