"""
Generate dbt/models/staging/yandex_market/_ym__sources.yml — every RAW table with every column documented.

Why a generator: the RAW layer has ~400 columns across 12 tables, and the reports grow (load_to_snowflake adds
columns as they appear). Column lists come from the local files in data/raw/ (scripts/raw_columns.py, no warehouse
needed); descriptions live in the dictionaries below (from the seller-API OpenAPI spec and the report docs, plus what
we learned from the data). A column without a description gets 'TODO' and a warning — the yaml never silently
drops a column.

Usage:
  python scripts/gen_sources_yml.py            # rewrite the yaml
  python scripts/gen_sources_yml.py --check    # exit 1 if the yaml is stale or any column is undocumented (CI)
"""
from __future__ import annotations

import pathlib
import sys

import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from raw_columns import raw_columns  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "dbt" / "models" / "staging" / "yandex_market" / "_ym__sources.yml"

HEADER = """\
# GENERATED by scripts/gen_sources_yml.py — edit the descriptions there, then re-run it. Do not edit by hand.
# Table names = <report dir>_<CSV sheet name> as produced by ingest/load_to_snowflake.table_name().
# Column lists come from the files in data/raw/; all RAW columns are VARCHAR (typing is staging's job).
# load_to_snowflake.py also pushes these descriptions into Snowflake as table / column COMMENTs.
"""

# ----------------------------------------------------------------------------------------------------------------
# Table-level metadata (order = order in the yaml). identifier = physical table in MARKETPLACE.RAW.
# ----------------------------------------------------------------------------------------------------------------
TABLES: list[dict] = [
    {
        "name": "united_orders_orders",
        "identifier": "UNITED_ORDERS_ORDERS_AND_OFFERS_TRANSACTIONS",
        "description": (
            "Sheet 'orders_and_offers_transactions' of the united-orders report (POST v2/reports/united-orders/generate): "
            "one row per order × SHOP_SKU × OFFER_STATUS (a partially unredeemed multi-unit order is split into a "
            "'Delivered to buyer' row and an 'Unredeemed…' row). No quantity column: TRANSFERRED_FOR_DELIVERY / "
            "DELIVERED_OR_RETURNED hold unit counts. CREATION_DATE, DELIVERY_DATE, SHIPMENT_DATE and all *_BANK_ORDER_DATE / "
            "*_HANDLING_TIME are DD.MM.YYYY; STATUS_CHANGED is YYYY-MM-DD HH24:MI:SS. The report window is NOT by creation "
            "date: a 2026-06-06..2026-09-03 request returned orders created from 2026-02-09. Without a subscription the API "
            "serves only the last 90 days. Report language = EN (values like 'Delivered to buyer')."
        ),
    },
    {
        "name": "united_orders_services",
        "identifier": "UNITED_ORDERS_SERVICES_AND_ORDERS_MARGIN",
        "description": (
            "Sheet 'services_and_orders_margin' of the united-orders report: one row per ORDER_ID with order-level status "
            "and every marketplace fee as a separate column (SALE_COMMISSION, BUYER_DELIVERY, BUYER_PAYMENT_ACCEPT/TRANSFER, "
            "LOYALTY_PROGRAM, BOOST, …), plus SUMMARY_COMMISSION, SUM_BILLING_PRICE_OF_ITEMS, INCOME_WITHOUT_SERVICES. "
            "Fees are per order — allocation to order lines happens in int_order_items_enriched. Fee benchmark for "
            "ORDERS_STATS.COMMISSIONS."
        ),
        "tests": {"ORDER_ID": ["unique", "not_null"]},
    },
    {
        "name": "united_orders_decoupling",
        "identifier": "UNITED_ORDERS_SERVICES_WITH_DECOUPLING",
        "description": (
            "Sheet 'services_with_decoupling' — orders sold through the marketplace's 'smart offer' (умное предложение: "
            "Market sells above the seller's price and splits the extra). Empty for this seller so far (header only). "
            "Not used."
        ),
    },
    {
        "name": "goods_turnover",
        "identifier": "GOODS_TURNOVER_TURNOVER",
        "description": (
            "Marketplace's own turnover report (POST v2/reports/goods-turnover/generate) for a given date, one row per "
            "SHOP_SKU × MACROREGION_NAME (Москва, Санкт-Петербург…). TURNOVER is a string: a number of days or 'Нет продаж'; "
            "AMOUNT may be '-'. Cast with try_to_decimal. Used as the reconciliation benchmark for stock/velocity marts. "
            "The date requested is in _SOURCE_FILE (…/<YYYY-MM-DD>/turnover.csv); a request for 'today' returns an empty file."
        ),
    },
    {
        "name": "stock_snapshots",
        "identifier": "STOCK_SNAPSHOTS",
        "description": (
            "SUPERSEDED on 2026-09-14 by stock_reports — kept as an archive of the 2026-09-03..2026-09-13 daily JSON "
            "snapshots, referenced by no model. Was: stock per offerId × warehouse_id from POST v2/campaigns/{id}/offers/stocks "
            "(current moment only, no history), STOCKS = JSON array [{type: FIT|AVAILABLE|FREEZE|…, count}], '[]' for "
            "an offer listed with no stock. Replaced because the report can be requested for any past date and holds "
            "end-of-day stock; the JSON snapshot for a missed cron day is lost forever (2026-09-04 was)."
        ),
    },
    {
        "name": "stock_reports",
        "identifier": "STOCK_REPORTS_STOCKS_ON_WAREHOUSES",
        "description": (
            "Stock per SHOP_SKU × WAREHOUSE on a past date — the 'Остатки на складах' report "
            "(POST v2/reports/stocks-on-warehouses/generate with reportDate; FBY). Backfilled daily for 2025-01-08..2026-09-02 "
            "(603 reports) because the JSON endpoint behind STOCK_SNAPSHOTS only knows the current day. The date is NOT a "
            "column: it is the folder in _SOURCE_FILE (stock_reports/<run_date>/<reportDate>/stocks_on_warehouses.csv), and "
            "the report holds the stock at the END of the day BEFORE reportDate (verified against the 2026-09-05 JSON snapshot: "
            "VALID = FIT to the unit, AVAILABLE_FOR_ORDER = AVAILABLE, RESERVED = FREEZE) → snapshot_date = reportDate − 1 in "
            "staging. Warehouses come as names, not ids (map in staging / dim_warehouses); warehouses with zero stock are "
            "omitted from the report; caps appear under their warehouse SKU (K1…K5) like in GOODS_TURNOVER_TURNOVER. "
            "Source of stg_ym__stock_levels since 2026-09-14; ingest/daily.sh requests reportDate = today every morning."
        ),
        "config": {"freshness": {"warn_after": {"count": 1, "period": "day"},
                                 "error_after": {"count": 3, "period": "day"}}},
    },
    {
        "name": "warehouses",
        "identifier": "WAREHOUSES",
        "description": (
            "FBY warehouses of the marketplace from GET v2/warehouses (one row per warehouse per daily snapshot, "
            "snapshot_date added by ingest/yandex_market.py): ID, NAME, ADDRESS as JSON text; _RAW_JSON holds the whole "
            "record. The bridge between the stock report, which prints warehouse NAMES, and orders / the old JSON "
            "snapshot, which carry warehouse ids. Small (≈10 rows); latest snapshot wins in stg_ym__warehouses. "
            "Warehouses that no longer exist (e.g. 'ЛО Парголово', 2025) may be absent — the staging keeps every id ever seen."
        ),
    },
    {
        "name": "orders_stats",
        "identifier": "ORDERS_STATS",
        "description": (
            "Full order history from POST v2/campaigns/{id}/stats/orders, one row per order per download (2025-01 → today, "
            "2 346 orders on 2026-09-04; no 90-day limit). Downloaded by quarter, so an order re-appears in every later "
            "file that covers its creation date — deduplicate in staging by ID, keeping the latest _LOADED_AT. Nested JSON "
            "is kept as text (ITEMS, COMMISSIONS, PAYMENTS, SUBSIDIES, DELIVERYREGION); _RAW_JSON holds the whole record. "
            "Primary source for fct_order_items; the united-orders report is the fee benchmark."
        ),
        "tests": {"ID": ["not_null"]},
    },
    {
        "name": "business_orders",
        "identifier": "BUSINESS_ORDERS",
        "description": (
            "Order history WITH the cancellation reason and the real delivery date, from POST v1/businesses/{id}/orders "
            "(2 383 orders on 2026-09-12, backfilled in 30-day windows by creation date — the API caps one request at 30 "
            "days and creationDateTo is EXCLUSIVE, so windows abut and an order appears in exactly one file; still "
            "deduplicate by ORDERID keeping the latest _LOADED_AT, because re-runs overlap). Exists because ORDERS_STATS "
            "carries neither SUBSTATUS nor any delivery date: there, every unredeemed parcel is CANCELLED_IN_DELIVERY and "
            "'never collected' cannot be told from 'refused at the counter'. Three fields here settle it — SUBSTATUS, "
            "DELIVERY.dates.realDeliveryDate (the day the goods reached the PICKUP POINT) and CANCELREQUESTED. Covers 100 % "
            "of the ORDERS_STATS orders (all 2 346 matched on 2026-09-12) plus 37 newer ones; getOrders would refuse orders "
            "cancelled over 30 days ago, this method does serve them. Nested JSON kept as text (ITEMS, PRICES, DELIVERY); "
            "_RAW_JSON holds the whole record. Money is NOT taken from here — fees live in ORDERS_STATS.COMMISSIONS."
        ),
        "tests": {"ORDERID": ["not_null"]},
    },
    {
        "name": "offer_mappings",
        "identifier": "OFFER_MAPPINGS",
        "description": (
            "Catalogue snapshot from POST v2/businesses/{id}/offer-mappings, one row per offer per download (51 SKUs). "
            "OFFER = seller-side product card, MAPPING = the marketplace card/category it is bound to. Source for "
            "dim_products; take the latest SNAPSHOT_DATE per offerId."
        ),
    },
    # goods-realization: monthly accounting report (POST v2/reports/goods-realization/generate), returned as XLSX and
    # tidied by ingest/realization_to_csv.py into one CSV per appendix. Month = REPORT_MONTH; no history limit.
    {
        "name": "goods_realization_shipped",
        "identifier": "GOODS_REALIZATION_SHIPPED",
        "description": (
            "Appendix 'shipped' (sheet 2) of the goods-realization report: units handed to delivery in REPORT_MONTH, by "
            "shipment date from the Market warehouse, one row per order line. Dates DD.MM.YYYY; amounts incl. VAT "
            "('Без НДС' for this seller); numbers arrive as '1.0'-style floats; ORDER_ID arrives in scientific notation — "
            "use PARTNER_ORDER_ID."
        ),
    },
    {
        "name": "goods_realization_delivered",
        "identifier": "GOODS_REALIZATION_DELIVERED",
        "description": (
            "Appendix 'delivered' (sheet 3): units delivered to the buyer in REPORT_MONTH, by delivery date, one row per "
            "order line with price before/after discounts and the discount split (marketplace promo / SberSpasibo / "
            "Yandex Plus). Financial truth for revenue — reconcile fct_sales_daily against it. Same formats as 'shipped'."
        ),
    },
    {
        "name": "goods_realization_unredeemed",
        "identifier": "GOODS_REALIZATION_UNREDEEMED",
        "description": (
            "Appendix 'unredeemed' (sheet 4): units the buyer did not collect, by the date they came back to the warehouse "
            "(UNREDEEMED_RECEIVED_DATE) in REPORT_MONTH. Same formats as 'shipped'."
        ),
    },
    {
        "name": "goods_realization_returned",
        "identifier": "GOODS_REALIZATION_RETURNED",
        "description": (
            "Appendix 'returned' (sheet 5): units returned by the buyer after delivery, by return-received date "
            "(RETURN_RECEIVED_DATE) in REPORT_MONTH. Same formats as 'shipped'."
        ),
    },
    {
        "name": "goods_realization_lost",
        "identifier": "GOODS_REALIZATION_LOST",
        "description": (
            "Appendix 'lost' (sheet 6): units lost by the marketplace's logistics and compensated to the seller "
            "(AUTO_COMPENSATION_*), and de-compensated if found later (DECOMPENSATION_*). Header only so far for this "
            "seller. Same formats as 'shipped'."
        ),
    },
]

SOURCE = {
    "name": "yandex_market",
    "description": "Raw exports from the marketplace seller API, loaded as-is (all VARCHAR) by ingest/load_to_snowflake.py.",
    "database": "MARKETPLACE",
    "schema": "RAW",
    "loader": "ingest/load_to_snowflake.py",
    "config": {
        "loaded_at_field": "_LOADED_AT::timestamp_ntz",
        "freshness": {"warn_after": {"count": 2, "period": "day"}, "error_after": {"count": 7, "period": "day"}},
    },
}

# ----------------------------------------------------------------------------------------------------------------
# Column descriptions. DOCS applies to a column name in any table; DOCS_BY_TABLE[identifier] overrides per table.
# Sources: seller-API OpenAPI spec (github.com/yandex-market/yandex-market-partner-api), report column docs at
# yandex.ru/dev/market/partner-api/doc/ru/reference/reports/…, ingest/realization_to_csv.py header mapping, and the data.
# ----------------------------------------------------------------------------------------------------------------
DOCS: dict[str, str] = {
    # --- technical, every table ---
    "_LOADED_AT": "UTC timestamp (ISO 8601) when load_to_snowflake.py wrote the row. Freshness field; with _SOURCE_FILE "
                  "it identifies a load batch.",
    "_SOURCE_FILE": "Path of the source file relative to data/raw/ (e.g. orders_stats/2026-09-04/2025-01-01_2025-03-31.jsonl). "
                    "Carries the download date and the requested period; replay / dedup key.",
    "_RAW_JSON": "The whole source record as JSON text — parse_json() in staging for anything not broken out into a column.",

    # --- united-orders report: seller block (identical on all three sheets) ---
    "BUSINESS_ID": "Business-account id ('ID бизнес-аккаунта'). Constant for this seller.",
    "MODEL": "Placement model ('Модели работы'): FBY (Market's warehouse and delivery) for every row here.",
    "PARTNER_ID": "Campaign / shop id ('ID магазинов'). Constant for this seller.",
    "SHOP_NAME": "Shop name as shown on the marketplace ('Названия магазинов').",
    "INN": "Seller's tax id ('ИНН'). Constant; not needed downstream.",
    "PLACEMENT_CONTRACT": "Placement contract number ('Номера договоров на размещение').",
    "PROMOTION_CONTRACT": "Promotion contract number ('Номера договоров на продвижение').",

    # --- united-orders report: order / line ---
    "ORDER_ID": "Marketplace order number ('Номер заказа'). Joins ORDERS_STATS.ID and GOODS_REALIZATION_*.PARTNER_ORDER_ID.",
    "PARTNER_ORDER_ID": "Seller's own order number ('Ваш номер заказа'); equals ORDER_ID for this seller (no external system).",
    "CREATION_DATE": "Order creation date ('Дата оформления'), DD.MM.YYYY.",
    "ORDER_TYPE": "Order type ('Тип заказа'): 'Sale to individual' for every row so far (B2B orders would differ).",
    "SHOP_SKU": "Seller's SKU ('Ваш SKU') — the product key across all sources (offerId / shopSku elsewhere).",
    "OFFER_NAME": "Product name as listed on the marketplace ('Название товара').",
    "PARTNER_PRICE_FOR_DELIVERY": "Seller's own price per unit at order time ('Ваша цена (за шт.)'), before marketplace "
                                  "discounts.",
    "BILLING_PRICE": "Selling price per unit ('Цена продажи (за шт.)') — what the buyer pays before marketplace-funded "
                     "discounts and points; the base for fee calculation.",
    "COFINANCE_TRESHOLD": "Seller's price-reduction threshold for co-financed ('скидки с Маркетом') discounts ('Ваш порог "
                          "снижения цены для участия в софинансировании'). Spelling is the report's. Empty for this seller.",
    "COFINANCE_VALUE": "Seller's share of a co-financed discount per unit ('Ваша скидка при софинансировании (за шт.)').",
    "COFINANCE_SUBSIDY": "Marketplace's share of a co-financed discount per unit ('Скидка Маркета при софинансировании').",
    "MARKETPLACE_SUBSIDY": "Other marketplace-funded discounts per unit ('Другие скидки Маркета (за шт.)') — promo the "
                           "marketplace pays for; reimbursed to the seller via NETTING_AMOUNT or MARKETPLACE_DISCOUNT_PAYMENT_*.",
    "SPASIBO": "Part of the price paid with SberSpasibo bonuses per unit ('Оплата бонусами СберСпасибо (за шт.)'). 0 so far.",
    "YANDEX_PLUS": "Part of the price paid with Yandex Plus points per unit ('Оплата баллами Яндекс Плюса (за шт.)').",
    "TRANSFERRED_FOR_DELIVERY": "Units handed to delivery ('Передано в доставку'). One of the two quantity columns; empty "
                                "on cancelled lines.",
    "DELIVERED_OR_RETURNED": "Units delivered, or returned / unredeemed — meaning depends on OFFER_STATUS "
                             "('Доставлено или возвращено').",
    "DELIVERY_DATE": "Delivery date ('Дата доставки заказа'), DD.MM.YYYY; empty until delivered.",
    "OFFER_STATUS": "Line status ('Статус товара'): Delivered to buyer | Shipped | Cancelled | Unredeemed in transit | "
                    "Unredeemed received | Unredeemed received in warehouse | Return in transit | Return received in warehouse.",
    "STATUS_CHANGED": "Timestamp of the last status change ('Статус изменен'), YYYY-MM-DD HH24:MI:SS, Moscow time.",
    "PAYMENT_TYPE": "Buyer's payment method ('Способ оплаты'): Prepayment with a bank card | Postpaid with a bound card | "
                    "Yandex Split (prepayment) | Postpaid Split | Postpaid Super Split | Faster Payments System. "
                    "'Postpaid…' = pay on receipt (drives the unredeemed rate).",
    "SHIPMENT_WAREHOUSE": "Market warehouse the order shipped from ('Склад отгрузки'), e.g. 'Яндекс.Маркет (Софьино)'.",
    "SHIPMENT_DATE": "Date the order left the warehouse ('Дата отгрузки'), DD.MM.YYYY.",
    "DELIVERY_REGION": "Delivery region name ('Регион доставки'), e.g. Москва, Санкт-Петербург.",
    "NETTING_AMOUNT": "Points credited to the seller's balance to cover marketplace-funded discounts ('Сумма баллов') — "
                      "netting instead of a bank transfer; usually equals MARKETPLACE_SUBSIDY.",
    "NETTING_TRANSACTION_STATUS": "Netting status ('Статус (справочно)'): Balance topped up | Balance will be topped up | "
                                  "empty (nothing to net).",

    # --- united-orders report: services sheet ---
    "ORDER_STATUS": "Order-level status ('Статус заказа'): Delivered | Not bought in stock (= unredeemed) | Canceled during "
                    "delivery | Canceled during processing | Order canceled before processing | Handed over for delivery | "
                    "Full return accepted at warehouse | Partially unclaimed orders accepted at warehouse | …",
    "SUMMARY_COMMISSION": "Total of all marketplace services for the order ('Все услуги Маркета за заказы') = sum of the "
                          "fee columns.",
    "SUM_BILLING_PRICE_OF_ITEMS": "Order total at selling price: sum of BILLING_PRICE × units over the order's lines "
                                  "(report header says 'Цена продажи (за шт.)' but the value is per order).",
    "INCOME_WITHOUT_SERVICES": "Income net of marketplace services ('Доход за вычетом услуг Маркета') = "
                               "SUM_BILLING_PRICE_OF_ITEMS − SUMMARY_COMMISSION.",
    "BUYER_PAYMENT": "Buyer's payment for the order ('Платёж покупателя'), excludes marketplace-funded discounts and Plus "
                     "points.",
    "BUYER_PAYMENT_STATUS": "Payout status ('Статус платежа покупателя'): Transferred | Will be transferred | Will not be "
                            "transferred because order was canceled.",
    "BANK_ORDER_ID": "Bank payment-order number of the payout ('Номер платежного поручения').",
    "SALE_COMMISSION": "Placement fee ('Размещение товаров на витрине') — the sale commission, % of BILLING_PRICE. "
                       "= ORDERS_STATS commission type FEE.",
    "WAREHOUSE_PROCESSING": "Warehouse handling fee ('Складская обработка'). Discontinued since 2024-01-01 — 0.",
    "LOYALTY_PROGRAM": "Loyalty programme and reviews-for-points fee ('Программа лояльности и отзывы'). "
                       "= LOYALTY_PARTICIPATION_FEE.",
    "BOOST": "Boost-for-sales fee, charged only on sales ('Буст продаж'). = AUCTION_PROMOTION.",
    "INSTALLMENT": "Instalment-plan fee ('Рассрочка'). Discontinued since 2022 — 0.",
    "BUYER_DELIVERY": "Delivery-to-buyer fee ('Доставка покупателю'). = DELIVERY_TO_CUSTOMER. Largest fee for this seller.",
    "CROSSREGIONAL_DELIVERY": "Middle-mile delivery fee ('Доставка (средняя миля)') for orders shipped to another region's "
                              "cluster.",
    "BUYER_EXPRESS_DELIVERY": "Express-delivery fee ('Экспресс-доставка покупателю'). 0 for FBY.",
    "CROSSBORDER_DELIVERY": "Cross-border delivery fee ('Доставка из-за рубежа'). 0.",
    "BUYER_PAYMENT_ACCEPT": "Payment-acceptance (acquiring) fee ('Приём платежа покупателя'). = AGENCY.",
    "BUYER_PAYMENT_TRANSFER": "Payment-transfer fee ('Перевод платежа покупателя'). = PAYMENT_TRANSFER.",
    "ORDER_INTAKE": "Pickup of orders from the seller's warehouse ('Организация забора заказов'); FBS only — 0.",
    "ORDER_PROCESSING": "Order processing at a sorting centre or pickup point ('Обработка заказов в СЦ или ПВЗ'); FBS only — 0.",
    "RESUPPLY_HANDLING": "Storage of unredeemed and returned items ('Хранение невыкупов и возвратов'). 0 so far.",
    "RETURN_RESUPPLY": "Return processing at the warehouse ('Обработка заказов на складе') — charged on unredeemed / "
                       "returned orders, 15 ₽ per unit here. = RETURN_PROCESSING.",
    "EXPROPRIATION_RESALE": "Marketplace's reward for selling goods the seller did not collect from the warehouse "
                            "('Вознаграждение за продажу товара'). 0.",

    # --- united-orders report: decoupling sheet (empty) ---
    "SHOP_ORDER_ID": "Seller's own order number (same as PARTNER_ORDER_ID on the other sheets).",
    "COUNT": "Units in the line ('Количество').",
    "SHOP_PRICE": "Seller's price per unit ('Ваша цена (за шт.)').",
    "SELLING_PRICE": "Marketplace's selling price per unit under the smart offer ('Цена продажи (за шт.)').",
    "EXTRA_INCOME": "Difference between the selling price and the seller's price ('Разница между вашей ценой и ценой продажи').",
    "EXTRA_DECOUPLING_MARGIN": "Extra revenue from the smart offer ('Доп. выручка от умного предложения').",
    "NET_DECOUPLING_GAIN": "Extra income from the smart offer after its fee ('Доп. доход от умного предложения').",
    "EXTRA_DECOUPLING_SALE_COMMISSION": "Additional placement fee charged on the smart-offer uplift.",
    "WAREHOUSE_HANDLING": "Warehouse handling fee ('Складская обработка') — same as WAREHOUSE_PROCESSING on the services sheet.",
    "DELIVERY": "Delivery-to-buyer fee — same as BUYER_DELIVERY on the services sheet.",
    "EXPRESS_DELIVERY": "Express-delivery fee — same as BUYER_EXPRESS_DELIVERY.",
    "PAYMENT_ACCEPTING": "Payment-acceptance fee — same as BUYER_PAYMENT_ACCEPT.",
    "PAYMENT_TRANSFER": "Payment-transfer fee — same as BUYER_PAYMENT_TRANSFER.",
    "RESUPPLY_STORAGE": "Storage of unredeemed and returned items — same as RESUPPLY_HANDLING.",
    "RESUPPLY_RETURN": "Return processing at the warehouse — same as RETURN_RESUPPLY.",

    # --- goods-turnover report ---
    "MACROREGION_NAME": "Warehouse cluster / macro-region ('Кластер'): Москва, Санкт-Петербург, Екатеринбург, Казань, Ростов…",
    "CATEGORY": "Marketplace category of the product ('Категория').",
    "MARKET_SKU": "Marketplace SKU — id of the product card on Market ('SKU на Маркете').",
    "LENGTH": "Package length, mm ('Длина, мм').",
    "WIDTH": "Package width, mm ('Ширина, мм').",
    "HEIGHT": "Package height, mm ('Высота, мм').",
    "VOLUME": "Package volume, litres ('Объём, л') — the unit storage is billed in.",
    "TURNOVER": "Turnover in days ('Оборачиваемость') = stock ÷ average daily sales; the string 'Нет продаж' when nothing "
                "sold in the period. Cast with try_to_decimal.",
    "AMOUNT": "Paid-storage cost for the period ('Стоимость платного хранения'); '-' when storage was free.",
    "MARKET_RECOMMENDATION": "Marketplace's free-text advice for the SKU in this cluster ('Рекомендация Маркета'): "
                             "increase supply / cut price / withdraw stock.",
    "AVG_SOLD_VOLUME": "Average daily volume sold, litres ('Среднесуточный объём проданных товаров, л').",
    "AVG_SOLD_ITEMS": "Average daily units sold ('Среднесуточное количество проданных товаров, шт.').",
    "AVG_SOLD_VOLUME_ON_STOCK": "Average daily volume in stock, litres ('Среднесуточный объём товаров на складе, л').",
    "ITEMS_ON_STOCK": "Units in stock on the last day of the period ('Остаток на последний день периода, шт.').",

    # --- goods-realization report (headers are Russian; mapping in ingest/realization_to_csv.py) ---
    "REPORT_MONTH": "Report month YYYY-MM (added by realization_to_csv.py from the folder name) — the accounting period "
                    "the row belongs to.",
    "APPENDIX": "Which appendix of the report the row came from (added by realization_to_csv.py): shipped | delivered | "
                "unredeemed | returned | lost.",
    "WAREHOUSE_SKU": "SKU under which the unit is stored at the warehouse ('SKU на складе'); may differ from SHOP_SKU "
                     "(e.g. K3) — do not join on it.",
    "UNITS_SHIPPED": "Units handed to delivery ('Количество переданных в доставку, шт.'), as '1.0'-style text.",
    "UNITS_DELIVERED": "Units delivered to the buyer ('Доставлено, шт.' / 'Количество доставленных, шт.').",
    "UNITS_UNREDEEMED": "Units not collected by the buyer ('Не выкуплено, шт.').",
    "UNITS_RETURNED": "Units returned after delivery ('Возвращено, шт.').",
    "ORDER_DATE": "Order creation date ('Дата оформления заказа'), DD.MM.YYYY.",
    "SHIPPED_DATE": "Date the unit was handed to delivery ('Дата передачи товара в доставку'), DD.MM.YYYY.",
    "DELIVERED_DATE": "Delivery date ('Дата доставки товара'), DD.MM.YYYY; empty when not delivered.",
    "UNREDEEMED_RECEIVED_DATE": "Date the unredeemed unit was received by the warehouse or sorting centre ('Дата приёма "
                                "невыкупа складом или сортировочным центром'), DD.MM.YYYY. Event date of this appendix.",
    "RETURN_RECEIVED_DATE": "Date the returned unit was received by the warehouse or sorting centre ('Дата приёма возврата "
                            "складом или сортировочным центром'), DD.MM.YYYY. Event date of this appendix.",
    "LOST_RECEIVED_DATE": "Date the lost order was received by the Market warehouse or handed back to the seller "
                          "('Дата приёма заказа складом Маркета или выдачи продавцу с СЦ'), DD.MM.YYYY.",
    "PAYMENT_METHOD": "Payment method ('Способ оплаты'): Предоплата | При получении | Яндекс.Сплит (предоплата) | "
                      "Постоплатный Сплит. 'При получении' / 'Постоплатный…' = paid on receipt.",
    "VAT_RATE": "VAT rate on the line ('Ставка НДС'); 'Без НДС' for this seller (simplified tax regime).",
    "PRICE_BEFORE_DISCOUNT": "Price per unit incl. VAT before any discounts, ₽ ('Цена c НДС без учёта скидок за шт.').",
    "DISCOUNT_MARKETPLACE_PROMO": "Seller-funded discount per unit under a marketplace promotion, ₽ ('Ваша скидка по акции "
                                  "маркетплейса на 1 шт.').",
    "DISCOUNT_SBER_SPASIBO": "Seller-funded discount per unit paid with SberSpasibo bonuses, ₽.",
    "DISCOUNT_YANDEX_PLUS": "Seller-funded discount per unit paid with Yandex Plus points, ₽.",
    "PRICE_AFTER_DISCOUNT": "Price per unit incl. VAT after all discounts, ₽ ('Цена с НДС с учётом всех скидок за шт.') — "
                            "the seller's realised price.",
    "TOTAL_BEFORE_DISCOUNT": "Line total before discounts, ₽ = PRICE_BEFORE_DISCOUNT × the appendix's unit count "
                             "('Стоимость всех … без учёта скидок').",
    "TOTAL_DISCOUNT": "Line total of all discounts, ₽ ('Сумма всех скидок').",
    "TOTAL_AFTER_DISCOUNT": "Line total after discounts, ₽ ('Стоимость всех … с учётом скидок') — revenue to reconcile "
                            "against.",
    "TOTAL_VAT": "VAT amount in the line total, ₽ ('Сумма НДС'); 0 for this seller.",
    "REDEEMED_AMOUNT": "Value of the units the buyer kept from a partially returned / unredeemed line, ₽ ('Стоимость "
                       "выкупленного товара'). Empty so far.",
    "CUSTOMS_DECLARATION_NO": "Customs declaration or traceability batch number (РНПТ) for imported / traceable goods. Empty.",
    "B2B_ORG_NAME": "Buyer organisation name for B2B orders ('Наименование организации'). Empty — B2C only.",
    "B2B_INN": "Buyer organisation tax id for B2B orders ('ИНН'). Empty.",
    "B2B_KPP": "Buyer organisation KPP for B2B orders ('КПП'). Empty.",
    "B2B_LEGAL_ADDRESS": "Buyer organisation legal address for B2B orders ('Юридический адрес'). Empty.",
    "UPD_STATUS": "Status of the universal transfer document (УПД) issued for a B2B order ('Статус УПД'). Empty.",
    "UPD_DATE": "Date of the УПД ('Дата УПД'). Empty.",
    "UPD_NO": "Number of the УПД ('Номер УПД'). Empty.",
    "UKD_STATUS": "Status of the universal correction document (УКД) for a B2B return ('Статус УКД'). Empty.",
    "UKD_DATE": "Date of the УКД ('Дата УКД'). Empty.",
    "UKD_NO": "Number of the УКД ('Номер УКД'). Empty.",
    "WAYBILL_DATE": "Date of the goods waybill (товарная накладная) for a B2B order. Empty.",
    "WAYBILL_NO": "Number of the goods waybill. Empty.",
    "INVOICE_DATE": "Date of the VAT invoice (счёт-фактура) for a B2B order. Empty.",
    "INVOICE_NO": "Number of the VAT invoice. Empty.",
    "CORRECTION_INVOICE_DATE": "Date of the corrective VAT invoice for a B2B return. Empty.",
    "CORRECTION_INVOICE_NO": "Number of the corrective VAT invoice. Empty.",
    "AUTO_COMPENSATION_DATE": "Date the marketplace automatically compensated the lost unit ('Дата автокомпенсации').",
    "AUTO_COMPENSATION_AMOUNT": "Compensation paid for the lost unit, ₽ ('Сумма автокомпенсации').",
    "DECOMPENSATION_DATE": "Date the compensation was reversed because the unit was found ('Дата декомпенсации').",
    "DECOMPENSATION_AMOUNT": "Amount reversed, ₽ ('Сумма декомпенсации').",

    # --- stats/orders (JSON keys, upper-cased by the loader) ---
    "ID": "Marketplace order id (int64). Joins UNITED_ORDERS_*.ORDER_ID and GOODS_REALIZATION_*.PARTNER_ORDER_ID. "
          "Not unique in RAW — one row per download that covered the order.",
    "CREATIONDATE": "Order creation date, YYYY-MM-DD.",
    "STATUSUPDATEDATE": "Date-time of the last status change, ISO 8601 with offset (+03:00, Moscow).",
    "STATUS": "Current order status: DELIVERED | CANCELLED_IN_DELIVERY (= unredeemed) | CANCELLED_IN_PROCESSING | "
              "CANCELLED_BEFORE_PROCESSING | RETURNED | PARTIALLY_DELIVERED | PARTIALLY_RETURNED | PICKUP | DELIVERY | "
              "PROCESSING | PENDING | RESERVED | UNPAID | LOST | UNKNOWN.",
    "PARTNERORDERID": "Order id in the seller's own system; equals ID for this seller.",
    "PAYMENTTYPE": "PREPAID (paid before receipt) | POSTPAID (paid on receipt) | UNKNOWN (cancelled / unpaid).",
    "FAKE": "false = real buyer order; true = marketplace test (sandbox) order — filter out.",
    "DELIVERYREGION": "JSON {id, name} of the delivery region, e.g. {\"id\": 213, \"name\": \"Москва\"}.",
    "BUYERTYPE": "PERSON (individual) | BUSINESS (organisation).",
    "CURRENCY": "Currency of all amounts in the order; RUR.",
    "ITEMS": "JSON array of order lines after any changes: [{offerName, marketSku, shopSku, count, "
             "prices [{type: BUYER|MARKETPLACE|CASHBACK, costPerItem, total}], warehouse {id, name}, "
             "details [{itemStatus: REJECTED|RETURNED, itemCount, updateDate, stockType}], bidFee, cofinanceThreshold, "
             "cofinanceValue, initialCount}]. prices.BUYER = price after all discounts; MARKETPLACE = marketplace coupons / "
             "promo; CASHBACK = Plus points. Delivery may appear as a line with offerName 'Доставка'. "
             "bidFee = boost bid in 1/100 %.",
    "COMMISSIONS": "JSON array of marketplace fees for the order: [{type, actual}], type ∈ FEE (placement) | "
                   "DELIVERY_TO_CUSTOMER | AGENCY (payment acceptance) | PAYMENT_TRANSFER | AUCTION_PROMOTION (boost) | "
                   "LOYALTY_PARTICIPATION_FEE | CROSSREGIONAL_DELIVERY | RETURN_PROCESSING | RETURNED_ORDERS_STORAGE | … "
                   "Empty ('[]') until the order is finally processed (e.g. DELIVERED).",
    "PAYMENTS": "JSON array of money transfers for the order: [{id, date YYYY-MM-DD, type: PAYMENT|REFUND, "
                "source: BUYER|MARKET_CESSION|CASHBACK|MARKETPLACE|SPLIT, total, paymentOrder}]. Empty while the order is "
                "only being processed or if cancelled before shipping.",
    "SUBSIDIES": "JSON array of marketplace points that reduce the placement fee: [{operationType: ACCRUAL|DEDUCTION, "
                 "type: SUBSIDY (marketplace promo/coupons) | YANDEX_CASHBACK (Plus) | DELIVERY, amount}]. Absent when none.",

    # --- offer-mappings ---
    "SNAPSHOT_DATE": "Download date YYYY-MM-DD (added by ingest/yandex_market.py). Take the latest per offer.",
    "OFFER": "JSON — seller-side product card: {offerId, name, vendor, category, pictures, description, barcodes, "
             "basicPrice {value, currencyId, discountBase}, purchasePrice, additionalExpenses, weightDimensions, cardStatus, "
             "campaigns, sellingPrograms, archived, groupId, …}. offerId = SHOP_SKU.",
    "MAPPING": "JSON — the marketplace card the offer is bound to: {marketSku, marketSkuName, marketCategoryId, "
               "marketCategoryName, marketModelId, marketModelName (deprecated 2026-10-12)}. Absent fields = not yet bound.",
    "SHOWCASEURLS": "JSON array of links to the product on Market's showcases: [{showcaseType, showcaseUrl}].",

    # --- stocks ---
    "OFFERID": "Seller's SKU (= SHOP_SKU) the stock row is for.",
    "WAREHOUSE_ID": "Market warehouse id the stock is held at (FBY: Market's warehouse), copied from the response's "
                    "warehouseId by ingest/yandex_market.py.",
    "STOCKS": "JSON array [{type, count}], type ∈ FIT (sellable or reserved) | AVAILABLE (sellable now) | FREEZE (reserved "
              "for orders) | QUARANTINE | DEFECT | EXPIRED | UTILIZATION. '[]' when the offer has no stock.",
    "UPDATEDAT": "Date-time the marketplace last updated this stock figure, ISO 8601 with offset. Absent for offers "
                 "without stock.",
}

# Payment blocks on the orders sheet: <PREFIX>_PAYMENT_{AMOUNT, BANK_ORDER_ID, BANK_ORDER_DATE, ID, HANDLING_TIME}
_PAYMENT_BLOCKS = {
    "BUYER": ("Payout of the buyer's payment to the seller", "Сумма платежа"),
    "MARKETPLACE_DISCOUNT": ("Payout reimbursing the marketplace-funded discount (MARKETPLACE_SUBSIDY + COFINANCE_SUBSIDY)",
                             "Сумма платежа"),
    "SPASIBO": ("Payout of the part paid with SberSpasibo bonuses", "Сумма платежа"),
    "YANDEX_PLUS": ("Payout of the part paid with Yandex Plus points", "Сумма платежа"),
    "REFUND_BUYER": ("Refund of the buyer's payment (cancelled / unredeemed / returned line)", "Сумма возврата"),
    "REFUND_MARKETPLACE_DISCOUNT": ("Reversal of the marketplace-discount payout", "Сумма возврата"),
    "REFUND_SPASIBO": ("Reversal of the SberSpasibo payout", "Сумма возврата"),
    "REFUND_YANDEX_PLUS": ("Reversal of the Yandex Plus payout", "Сумма возврата"),
    "DEFECT_REFUND": ("Amount withheld from the seller for a defective-item refund", "Удержанная сумма"),
}
for _p, (_what, _ru) in _PAYMENT_BLOCKS.items():
    DOCS[f"{_p}_PAYMENT_AMOUNT"] = f"{_what}: amount, ₽ ('{_ru}'). Empty when no such transfer."
    DOCS[f"{_p}_PAYMENT_BANK_ORDER_ID"] = f"{_what}: bank payment-order number ('Номер платежного поручения')."
    DOCS[f"{_p}_PAYMENT_BANK_ORDER_DATE"] = f"{_what}: bank payment-order date ('Дата платежного поручения'), DD.MM.YYYY."
    DOCS[f"{_p}_PAYMENT_ID"] = f"{_what}: payment identifier ('Идентификатор платежа')."
    DOCS[f"{_p}_PAYMENT_HANDLING_TIME"] = f"{_what}: payment-register date ('Дата реестра платежей'), DD.MM.YYYY."

DOCS_BY_TABLE: dict[str, dict[str, str]] = {
    "GOODS_REALIZATION_SHIPPED": {},
    "GOODS_REALIZATION_DELIVERED": {},
    "GOODS_REALIZATION_UNREDEEMED": {},
    "GOODS_REALIZATION_RETURNED": {},
    "GOODS_REALIZATION_LOST": {},
}
for _t in DOCS_BY_TABLE:
    DOCS_BY_TABLE[_t].update({
        "ORDER_ID": "Marketplace order number ('Номер заказа') — arrives from the XLSX in scientific notation "
                    "(5.7713802176E10), so it loses digits: use PARTNER_ORDER_ID instead.",
        "PARTNER_ORDER_ID": "Seller's order number ('Ваш номер заказа') = the marketplace order number as exact text. "
                            "Join key to ORDERS_STATS.ID and UNITED_ORDERS_*.ORDER_ID.",
        "ORDER_TYPE": "Order type ('Тип заказа'): 'Продажа физлицу' (sale to an individual) for every row so far.",
        "SHOP_SKU": "Seller's SKU ('Ваш SKU') — product key; join to OFFER_MAPPINGS / ORDERS_STATS items.",
    })
DOCS_BY_TABLE["GOODS_TURNOVER_TURNOVER"] = {
    "SHOP_SKU": "Seller's SKU ('Ваш SKU').",
    "OFFER_NAME": "Product name ('Название товара').",
}
DOCS_BY_TABLE["STOCK_REPORTS_STOCKS_ON_WAREHOUSES"] = {
    "SHOP_SKU": "Seller's SKU ('Ваш SKU'); caps come as the warehouse SKU (K1…K5) — resolve via dim_products.warehouse_sku.",
    "ARTICLE": "Seller's article ('Артикул') — equals SHOP_SKU in every row so far.",
    "MARKET_SKU": "Marketplace SKU ('SKU на Маркете').",
    "PRODUCT_NAME": "Product name on the card ('Название товара').",
    "VALID": "Good stock, units ('Годный') = FIT in the JSON snapshot: AVAILABLE_FOR_ORDER + RESERVED.",
    "RESERVED": "Units reserved for placed orders ('Резерв') = FREEZE in the JSON snapshot.",
    "AVAILABLE_FOR_ORDER": "Units buyers can order right now ('Доступно для заказа') = AVAILABLE in the JSON snapshot.",
    "QUARANTINE": "Units in quarantine ('Карантин') — awaiting a decision after intake / return; not sellable.",
    "UTILIZATION": "Units handed over for disposal ('Передан на утилизацию').",
    "DEFECT": "Defective units ('Брак').",
    "EXPIRED": "Expired units ('Просрочен') — never for apparel.",
    "LENGTH": "Package length, mm ('Длина, мм') — 0 in the backfill.",
    "WIDTH": "Package width, mm ('Ширина, мм') — 0 in the backfill.",
    "HEIGHT": "Package height, mm ('Высота, мм') — 0 in the backfill.",
    "WEIGHT": "Package weight, kg ('Вес, кг') — 0 in the backfill.",
    "WAREHOUSE": "Warehouse NAME ('Склад'), e.g. 'МО Софьино (кроме КГТ) - 1', 'ЛО Шушары', 'Ростов-на-Дону-2' — the JSON "
                 "snapshot uses warehouse ids; map name → id in staging. 'ЛО Парголово' appears only in 2025.",
    "SELLING_STATUS": "Selling status text ('Статус продаж'): 'Продажи идут', 'Нет на складе', …",
    "RECOMMENDATIONS": "Marketplace's replenishment recommendation text ('Рекомендации'); mostly empty.",
    "TURNOVER": "Turnover in days ('Оборачиваемость') as text, or 'Нет продаж' — cast with try_to_decimal.",
}
DOCS_BY_TABLE["WAREHOUSES"] = {
    "SNAPSHOT_DATE": "Day the list was pulled (added by ingest/yandex_market.py); one pull per day by cron.",
    "ID": "Marketplace warehouse id — the value orders and the old STOCK_SNAPSHOTS carry (172 = МО Софьино, 313 = ЛО Шушары, "
          "305 = Ростов-на-Дону-2, 300 = Екатеринбург, 302 = Самара, 501 = Домодедово возвратный).",
    "NAME": "Warehouse name as the marketplace prints it — must match STOCK_REPORTS_STOCKS_ON_WAREHOUSES.WAREHOUSE exactly; "
            "int_stock_daily joins on it and warns on any name it cannot resolve.",
    "ADDRESS": "JSON {city, street, number, building, block, gps {latitude, longitude}} — kept as text.",
}
DOCS_BY_TABLE["UNITED_ORDERS_SERVICES_WITH_DECOUPLING"] = {
    "ORDER_ID": "Marketplace order number ('Номер заказа').",
}


DOCS_BY_TABLE["BUSINESS_ORDERS"] = {
    "ORDERID": "Marketplace order id. Joins ORDERS_STATS.ID, UNITED_ORDERS_*.ORDER_ID and GOODS_REALIZATION_*.PARTNER_ORDER_ID. "
               "One row per order per download.",
    "EXTERNALORDERID": "Order id in the seller's own system; equals ORDERID for this seller.",
    "CAMPAIGNID": "Campaign / shop id. Constant for this seller.",
    "PROGRAMTYPE": "Placement model of the shop: FBY for every row here.",
    "STATUS": "Order status in the ORDERS vocabulary, which is NOT the ORDERS_STATS one: CANCELLED (not "
              "CANCELLED_IN_DELIVERY / _IN_PROCESSING / _BEFORE_PROCESSING), DELIVERED, DELIVERY, PICKUP, PROCESSING, "
              "RETURNED, PARTIALLY_RETURNED, PENDING, UNPAID. Which kind of cancellation it was is not here — read it from "
              "ORDERS_STATS.STATUS, and the REASON from SUBSTATUS.",
    "SUBSTATUS": "Processing stage (STATUS = PROCESSING) or CANCELLATION REASON (STATUS = CANCELLED). Filled on every row. "
                 "Do NOT read it as the buyer's reason on its own: USER_CHANGED_MIND ('cancelled for personal reasons') sits "
                 "on 351 unredeemed orders where the parcel had already reached the pickup point and nobody asked to cancel. "
                 "The reason is a combination of SUBSTATUS, realDeliveryDate and CANCELREQUESTED — see int_order_lines. "
                 "Values seen on unredeemed orders (693 on 2026-09-12): USER_CHANGED_MIND 380, PICKUP_EXPIRED 119, "
                 "FULL_NOT_RANSOM 83 (undocumented; literally 'full non-purchase'), USER_HAS_NO_TIME_TO_PICKUP_ORDER 13, "
                 "USER_BOUGHT_CHEAPER 18, REPLACING_ORDER 12, USER_REFUSED_QUALITY 8, DELIVERY_SERVICE_UNDELIVERED 8, "
                 "USER_REFUSED_PRODUCT 6, USER_WANTS_TO_CHANGE_ADDRESS 9, CUSTOM 10, and a tail of one-offs. The enum is open: "
                 "the docs say other values may appear and need not be handled.",
    "CREATIONDATE": "Order creation timestamp, ISO 8601 with the +03:00 (Moscow) offset. The field the backfill windows "
                    "filter on.",
    "UPDATEDATE": "Timestamp of the last change, ISO 8601 with offset. On a cancelled order this is the moment of "
                  "cancellation — compared with DELIVERY.dates.realDeliveryDate it says whether the parcel was ended inside "
                  "the pickup-point storage window (7 days at a Market outlet, 2 in a locker) or after it expired. The data "
                  "shows the shape: 167 unredeemed orders ended the day the parcel arrived, then a second bump of 73 on day 8.",
    "CANCELREQUESTED": "TRUE when the BUYER asked to cancel (in the app), FALSE when the cancellation came from the "
                       "marketplace's own processing. The documented filter is DBS-only, but the field is returned for FBY "
                       "and is the cleanest split between 'changed their mind remotely' and 'the parcel was ended at the "
                       "counter': 101 of 740 unredeemed orders have TRUE.",
    "DELIVERY": "JSON of the delivery: {type: PICKUP|DELIVERY|POST, serviceName, deliveryServiceId, warehouseId, "
                "deliveryPartnerType, dispatchType (MARKET_BRANDED_OUTLET = a Market pickup point, UNKNOWN otherwise), "
                "dates {fromDate, toDate, fromTime, toTime, realDeliveryDate}}. **realDeliveryDate is the reason this source "
                "exists**: documented as the day the goods reached the pickup point (for self-pickup) or the buyer (for a "
                "courier), YYYY-MM-DD in the data although the spec says DD.MM.YYYY. Filled on 2 183 of 2 383 orders; on 639 "
                "of the 693 unredeemed ones — so 92 % of unredeemed parcels did reach the pickup point and only 54 were "
                "cancelled before arrival. fromDate/toDate are the PLANNED window, not the fact. Every unredeemed order so "
                "far is type = PICKUP: courier orders in this brand's history never end as an unredeemed parcel.",
    "ITEMS": "JSON array of the order lines: [{id, offerId (= shopSku), offerName, count, prices {payment, subsidy, vat}, "
             "instances [{cis}], requiredInstanceTypes, itemStatuses [{status: CREATED|SHIPPED|CANCELLED|DELIVERED_TO_BUYER|"
             "LOST|REJECTED|RETURNED, count}]}]. itemStatuses is a per-unit status count and a cross-check on "
             "ORDERS_STATS.ITEMS[].details, which is what the models use; prices here are per unit and are NOT the fee basis.",
    "PRICES": "JSON {payment, subsidy} for the whole order: what the buyer pays and the marketplace-funded part. "
              "Benchmark only — revenue is built from ORDERS_STATS prices, which reconcile with the realization report.",
    "PAYMENTTYPE": "PREPAID (paid before receipt) | POSTPAID (paid on receipt) — the strongest predictor of an unredeemed "
                   "parcel in this data (11 % vs 59 %).",
    "PAYMENTMETHOD": "How it was paid: YANDEX (card on the marketplace), CARD_ON_DELIVERY, CASH_ON_DELIVERY, CREDIT, …",
    "BUYERTYPE": "PERSON (individual) | BUSINESS (organisation).",
    "FAKE": "TRUE = marketplace test order. No test orders came back in the backfill (the endpoint excludes them unless "
            "asked), but keep the filter downstream.",
    "SOURCEPLATFORM": "Where the order was placed: MARKET, and other platforms of the ecosystem.",
    "NOTES": "Free-text note attached to the order (present on 196 orders). Not used downstream; may hold support comments.",
}


def describe(table: str, col: str) -> str | None:
    return DOCS_BY_TABLE.get(table, {}).get(col) or DOCS.get(col)


def build() -> tuple[dict, list[str]]:
    cols = raw_columns()
    missing: list[str] = []
    tables_out = []
    for t in TABLES:
        ident = t["identifier"]
        entry: dict = {"name": t["name"], "identifier": ident, "description": t["description"]}
        if "config" in t:
            entry["config"] = t["config"]
        columns = []
        # A source documented before its first download (DOCS_BY_TABLE lists its columns) is emitted from the docs, so
        # `dbt parse` resolves source() while the data is still on its way; raw_columns --check reconciles once it lands.
        table_cols = cols.get(ident) or list(DOCS_BY_TABLE.get(ident, {}))
        for c in table_cols:
            d = describe(ident, c)
            if d is None:
                missing.append(f"{ident}.{c}")
                d = "TODO"
            col_entry: dict = {"name": c, "description": d}
            tests = t.get("tests", {}).get(c)
            if tests:
                col_entry["data_tests"] = tests
            columns.append(col_entry)
        if ident not in cols and not table_cols:
            missing.append(f"{ident}: no local data in data/raw — columns unknown")
        entry["columns"] = columns
        tables_out.append(entry)
    for ident in cols:
        if ident.startswith("COGS_"):        # partner cost file: documented by hand in models/staging/finance/_finance__sources.yml
            continue
        if ident not in {t["identifier"] for t in TABLES}:
            missing.append(f"{ident}: table in data/raw but not in TABLES")
    doc = {"version": 2, "sources": [{**SOURCE, "tables": tables_out}]}
    return doc, missing


class _Dumper(yaml.SafeDumper):
    """Folded block scalars (>-) for prose, so quotes and colons don't turn into ''escaped'' single-quoted strings."""

    def increase_indent(self, flow=False, indentless=False):   # indent list items under their key
        return super().increase_indent(flow, False)


def _str(dumper: yaml.SafeDumper, value: str):
    if len(value) > 90 or any(ch in value for ch in "':#"):
        return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=">")
    return dumper.represent_scalar("tag:yaml.org,2002:str", value)


_Dumper.add_representer(str, _str)


def render(doc: dict) -> str:
    body = yaml.dump(doc, Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=118, default_flow_style=False)
    return HEADER + "\n" + body


if __name__ == "__main__":
    doc, missing = build()
    text = render(doc)
    for m in missing:
        print(f"WARNING: {m}", file=sys.stderr)
    if "--check" in sys.argv:
        stale = not OUT.exists() or OUT.read_text(encoding="utf-8") != text
        if stale:
            print(f"{OUT.relative_to(ROOT)} is stale — run scripts/gen_sources_yml.py", file=sys.stderr)
        sys.exit(1 if (stale or missing) else 0)
    OUT.write_text(text, encoding="utf-8")
    n = sum(len(t["columns"]) for t in doc["sources"][0]["tables"])
    print(f"wrote {OUT.relative_to(ROOT)}: {len(doc['sources'][0]['tables'])} tables, {n} columns, "
          f"{len(missing)} undocumented")
